codeunit 50005 "Mail Management Altran"
{
    trigger OnRun()
    begin

    end;

    procedure SendMailSalesInvoice(SalesInvoiceHeader: Record "Sales Invoice Header"): Boolean
    var
        //POReport2: Report 50062;
        Customer: Record Customer;
        PurchSetup: Record "Purchases & Payables Setup";
        EMailSend: Codeunit Email;
        EMailMsg: Codeunit "Email Message";
        Location1: Record Location;
        LocationName: text[50];
        OStream: OutStream;
        FileExist: Boolean;
        RecRef: RecordRef;
        Fref: FieldRef;
        FileName: Text;
        CompInfo: Record "Company Information";
        Reciepients: list of [Text[100]];
    begin
        CompInfo.GET;
        B.CreateOutStream(OStream);

        RecRef.Open(Database::"Sales Invoice Header");
        Fref := RecRef.Field(3);
        Fref.SETRANGE(SalesInvoiceHeader."No.");
        FileName := 'SalesInvoice' + DELCHR(SalesInvoiceHeader."No.", '=', '/\.') + '.pdf';
        //POReport2.UseRequestPage(false);
        Report.SaveAs(60012, '', ReportFormat::Pdf, OStream, RecRef);
        FileExist := true;
        b.CreateInStream(IStream);
        IF Customer.GET(SalesInvoiceHeader."Sell-to Customer No.") THEN BEGIN
            Customer.TestField("E-Mail");
            Subject := 'Invoice Generated by BYJUs - ' + Customer.Name + ' - [' + SalesInvoiceHeader."No." + ']';

            BodyText := 'Dear' + ' ' + SalesInvoiceHeader."Sell-to Customer Name" + ',' + '<BR>' + '<BR>';

            BodyText := BodyText + 'Welcome to BYJUs,' + '<br><br>';

            //BodyText := BodyText + ' ' + 'The following Tax-Invoice/Prepayment Invoice is generated dated  <B> ' + FORMAT(SalesInvoiceHeader."Posting Date") + '</B> ,  Customer Invoice Number <B> ' + SalesInvoiceHeader."No." + '.</B><BR>' + '<BR>';
            BodyText := BodyText + 'Thank you for choosing Byjus as your learning Companion.<br><br>';

            BodyText := BodyText + 'Kindly find the attached Prepayment invoice/TAX invoice with Terms and Conditions. <br><br>';
            BodyText := BodyText + 'For any queries or changes, please contact us on ' + CompInfo."Phone No." + '<br><br>';
            BodyText := BodyText + 'Kindly refer to the below link for the Terms and Conditions:<br>';
            BodyText := BodyText + 'https://moreideas.ae/bfs/terms-conditions.html<br>https://www.moreideas.ae/terms-conditions/<br><br>';
            //BodyText := BodyText + '<I>This is computer generated copy and no signature is required. </I>' + '<BR>' + '<BR>';
            BodyText := BodyText + 'Welcome aboard,' + '<br>';
            BodyText := BodyText + 'Team BYJUs' + '<br>';
            //BodyText := BodyText + '<br letter-spacing: 5px> <I>*Please do not reply to this mail. It is an auto-generated mail.' + '<BR>';
            BodyText := BodyText + CompInfo."E-Mail";
            EMailMsg.Create(Customer."E-Mail", Subject, BodyText, true);
            //EMailMsg.Create('bayastheen.j@gmail.com', Subject, BodyText, true); //lynisha@moreideas.ae
            // EMailMsg.AddRecipient(enum::"Email Recipient Type"::bCc, 'kulwant@olsim.com');

            EMailMsg.AddAttachment(FileName, 'application/pdf', Base64.ToBase64(IStream));
            Mail.Enqueue(EMailMsg, EmailScenerio::Default);
            exit(TRUE);
        END;
    end;

    procedure SendMailSalesOrder(SalesHeader: Record "Sales Header"): Boolean
    var
        //POReport2: Report 50062;
        Customer: Record Customer;
        PurchSetup: Record "Purchases & Payables Setup";
        EMailSend: Codeunit Email;
        EMailMsg: Codeunit "Email Message";
        Location1: Record Location;
        LocationName: text[50];
        OStream: OutStream;
        FileExist: Boolean;
        RecRef: RecordRef;
        Fref: FieldRef;
        FileName: Text;
        CompInfo: Record "Company Information";
        Reciepients: list of [Text[100]];
        User: Record User;
    begin
        CompInfo.GET;
        B.CreateOutStream(OStream);

        RecRef.Open(Database::"Sales Header");
        Fref := RecRef.Field(3);
        Fref.SETRANGE(SalesHeader."No.");
        FileName := 'SalesOrder' + DELCHR(SalesHeader."No.", '=', '/\.') + '.pdf';
        //POReport2.UseRequestPage(false);
        Report.SaveAs(50018, '', ReportFormat::Pdf, OStream, RecRef);
        FileExist := true;
        b.CreateInStream(IStream);
        IF Customer.GET(SalesHeader."Sell-to Customer No.") THEN BEGIN
            Customer.TestField("E-Mail");
            User.Setrange("User Name", UserId);
            if User.FindFirst() Then;
            Subject := 'Order Generated for - ' + Customer.Name + ' - [' + SalesHeader."No." + ']';

            BodyText := 'Dear' + ' ' + SalesHeader."Sell-to Customer Name" + ',' + '<BR>' + '<BR>';

            BodyText := BodyText + 'This is to confirm that we have received your order ' + SalesHeader."No." + 'Placed on ' + FORMAT(SalesHeader."Order Date") + '<br><br>';
            BodyText := BodyText + 'Our team is now processing your order, and we’ll provide updates as it progresses. Should you have any questions or require additional information, please don’t hesitate to contact us. <br><br>';
            BodyText := BodyText + 'Thank you for choosing ' + CompInfo.Name + '.. We appreciate your business!' + '<br><br>';
            BodyText := BodyText + 'Best regards, ' + '<br><br>';
            BodyText := BodyText + User."Full Name" + '<br><br>';

            EMailMsg.Create(Customer."E-Mail", Subject, BodyText, true);

            EMailMsg.AddAttachment(FileName, 'application/pdf', Base64.ToBase64(IStream));
            Mail.Enqueue(EMailMsg, EmailScenerio::Default);
            exit(TRUE);
        END;
    end;

    var
        Subject: Text[250];
        EmailScenerio: Enum "Email Scenario";
        BodyText: Text[1024];
        IStream: InStream;
        OStream: OutStream;
        Base64: Codeunit "Base64 Convert";
        Mail: Codeunit Email;
        EMailMsg: Codeunit "Email Message";
        b: Codeunit "Temp Blob";
}